version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ep-gentle-pine-a4segogl-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
      KC_DB_USERNAME: neondb_owner
      KC_DB_PASSWORD: npg_tkcfe73ALCWK
      KC_IMPORT: /opt/keycloak/data/import/Ahssane-voyage-realm.json
    volumes:
      - ./Ahssane-voyage-realm.json:/opt/keycloak/data/import/Ahssane-voyage-realm.json
    ports:
      - "8080:8080"
    networks:
      - local

networks:
  local:
    driver: bridge
